spring:
  application:
    name: "umc_9th"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/umc9th
    username: root
    password: 1234

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      # (참고) 개발 중에는 'update', 배포 시에는 'validate' 또는 'none' 권장
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  token:
    # ⚠️ 중요: 특수문자와 공백이 포함된 키 값은 반드시 큰따옴표("")로 감싸야 합니다.
    secretKey: "ZGh3YWlkc2F2ZXdhZXZ3b2EgMTM5ZXUgMDMxdWMyIHEyMiBAIDAgKTJFVio="
    expiration:
      access: 14400000