spring:
  application:
    name: "umc_9th"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/umc9th
    username: root
    password: 1234

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      # (경고) 테이블 생성 후 반드시 'validate'로 변경하세요.
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true